name: lab_decide-github-actions

on: # Is run every time someone pushes a change to the repository or merges a PR to the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: # Group together jobs.
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Checks out the repository so the workflow (this) can use it.
    - name: Set up Python 3.10
      uses: actions/setup-python@v2 # Sets up python with the subsequently mentioned python version.
      with:
        python-version: "3.10"

    - name: Install dependencies # Installs required dependencies.
      # Current dependencies include: Flake8 and Numpy.
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi